# Generated by Django 5.2.7 on 2025-10-21 01:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Unique code for identifying the warehouse.', max_length=20, unique=True, verbose_name='Warehouse Code')),
                ('name', models.CharField(max_length=100, verbose_name='Warehouse Name')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Location')),
                ('capacity', models.PositiveIntegerField(blank=True, help_text='Maximum storage capacity of the warehouse (in units or pallets).', null=True)),
                ('manager', models.CharField(blank=True, max_length=100, null=True, verbose_name='Manager Name')),
                ('address_line1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address Line 1')),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address Line 2')),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_number', models.CharField(blank=True, help_text='Enter a contact phone number for the warehouse.', max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Warehouse',
                'verbose_name_plural': 'Warehouses',
                'ordering': ['name'],
            },
        ),
    ]
