# Generated by Django 5.2.7 on 2025-10-21 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='warehouse',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='address_line1',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='address_line2',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='city',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='country',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='location',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='state',
        ),
        migrations.AddField(
            model_name='warehouse',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='manager',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
