# Generated by Django 5.2.7 on 2025-10-21 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_alter_warehouse_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='manager',
        ),
    ]
